//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad_mga
    {
        public actividad_mga()
        {
            this.actividad = new HashSet<actividad>();
            this.insumo = new HashSet<insumo>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int lis_detalle_id_etapa { get; set; }
        public int producto_id { get; set; }
    
        public virtual ICollection<actividad> actividad { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual producto producto { get; set; }
        public virtual ICollection<insumo> insumo { get; set; }
    }
}
