//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad_detalle
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> cantidad_avance { get; set; }
        public int actividad_id { get; set; }
        public Nullable<double> porc_ejecutado { get; set; }
    
        public virtual actividad actividad { get; set; }
    }
}
