//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuerdoAprobacion
    {
        public int idAcuerdoAprobacion { get; set; }
        public string numeroAcuerdo { get; set; }
        public string fechaAcuerdo { get; set; }
        public Nullable<int> valorAcuerdo { get; set; }
        public Nullable<int> vigencia { get; set; }
        public int fuente_financiacion_id { get; set; }
        public int proyecto_bpin { get; set; }
        public int lis_detalle_id_ocad { get; set; }
    
        public virtual fuente_financiacion fuente_financiacion { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual proyecto proyecto { get; set; }
    }
}
