//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria
    {
        public int id { get; set; }
        public string tipo_foro { get; set; }
        public string nombre_foro { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string grupo_encargado { get; set; }
        public Nullable<int> asistentes { get; set; }
        public Nullable<bool> acompanamiento { get; set; }
        public string grupo_acompanamiento { get; set; }
        public int proyecto_bpin { get; set; }
        public int lis_detalle_id_municipio { get; set; }
    
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual proyecto proyecto { get; set; }
    }
}
