//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactoEntidadEjecutora
    {
        public contactoEntidadEjecutora()
        {
            this.contactoEntidadEjecutora_has_entidadEjecutora = new HashSet<contactoEntidadEjecutora_has_entidadEjecutora>();
        }
    
        public int idContactoEntidad { get; set; }
        public string tipoId { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telFijo { get; set; }
        public string email { get; set; }
        public string estado { get; set; }
        public string telCelular { get; set; }
        public string tipoContacto { get; set; }
        public Nullable<bool> representanteLegal { get; set; }
    
        public virtual ICollection<contactoEntidadEjecutora_has_entidadEjecutora> contactoEntidadEjecutora_has_entidadEjecutora { get; set; }
    }
}
