//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactoEntidadEjecutora_has_entidadEjecutora
    {
        public int entidadEjecutora_idEntidadEjecutora1 { get; set; }
        public int contactoEntidadEjecutora_idContactoEntidad1 { get; set; }
        public int id { get; set; }
    
        public virtual contactoEntidadEjecutora contactoEntidadEjecutora { get; set; }
        public virtual entidadEjecutora entidadEjecutora { get; set; }
    }
}
