//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuente_financiacion
    {
        public fuente_financiacion()
        {
            this.acuerdoAprobacion = new HashSet<acuerdoAprobacion>();
            this.fuente_financiacion_detalle = new HashSet<fuente_financiacion_detalle>();
            this.fuente_financiacion_has_proyecto = new HashSet<fuente_financiacion_has_proyecto>();
            this.incorporacion_presupuestal = new HashSet<incorporacion_presupuestal>();
        }
    
        public int id { get; set; }
        public string fuente_financiacioncol { get; set; }
        public int lis_detalle_id_etapa { get; set; }
        public int lis_detalle_id_tipoenttidad { get; set; }
        public int lis_detalle_id_tiporecurso { get; set; }
        public int lis_detalle_id_identidad { get; set; }
    
        public virtual ICollection<acuerdoAprobacion> acuerdoAprobacion { get; set; }
        public virtual ICollection<fuente_financiacion_detalle> fuente_financiacion_detalle { get; set; }
        public virtual ICollection<fuente_financiacion_has_proyecto> fuente_financiacion_has_proyecto { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual lis_detalle lis_detalle1 { get; set; }
        public virtual lis_detalle lis_detalle2 { get; set; }
        public virtual lis_detalle lis_detalle3 { get; set; }
        public virtual ICollection<incorporacion_presupuestal> incorporacion_presupuestal { get; set; }
    }
}
