//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class incorporacion_presupuestal
    {
        public int id { get; set; }
        public Nullable<int> numero_acto_administrativo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> vigencia { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<bool> aplica_vigencia_futura { get; set; }
        public Nullable<int> numero_autorizacion_futura { get; set; }
        public int proyecto_bpin { get; set; }
        public int lis_detalle_id_tipo_acto_adm { get; set; }
        public int lis_detalle_id_tipo_vigencia_futura { get; set; }
        public int rubro_id { get; set; }
        public int fuente_financiacion_id { get; set; }
    
        public virtual fuente_financiacion fuente_financiacion { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual lis_detalle lis_detalle1 { get; set; }
        public virtual proyecto proyecto { get; set; }
        public virtual rubro rubro { get; set; }
    }
}
