//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicador_producto
    {
        public indicador_producto()
        {
            this.indicador_producto_detalle = new HashSet<indicador_producto_detalle>();
        }
    
        public int id { get; set; }
        public int lista_indicador_id { get; set; }
        public int producto_id { get; set; }
    
        public virtual ICollection<indicador_producto_detalle> indicador_producto_detalle { get; set; }
        public virtual lista_indicador lista_indicador { get; set; }
        public virtual producto producto { get; set; }
    }
}
