//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicador_producto_detalle
    {
        public int id { get; set; }
        public int indicador_producto_id { get; set; }
        public Nullable<int> vigencia { get; set; }
        public Nullable<double> valor { get; set; }
    
        public virtual indicador_producto indicador_producto { get; set; }
    }
}
