//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class insumo
    {
        public int id { get; set; }
        public Nullable<int> vigencia { get; set; }
        public Nullable<double> valor { get; set; }
        public int actividad_id { get; set; }
        public int lis_detalle_id_tipo { get; set; }
    
        public virtual actividad_mga actividad_mga { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
    }
}
