//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class lis_detalle
    {
        public lis_detalle()
        {
            this.actividad = new HashSet<actividad>();
            this.actividad_mga = new HashSet<actividad_mga>();
            this.acuerdoAprobacion = new HashSet<acuerdoAprobacion>();
            this.auditoria = new HashSet<auditoria>();
            this.cuenta = new HashSet<cuenta>();
            this.cumplimiento_requisitos = new HashSet<cumplimiento_requisitos>();
            this.fuente_financiacion = new HashSet<fuente_financiacion>();
            this.fuente_financiacion1 = new HashSet<fuente_financiacion>();
            this.fuente_financiacion2 = new HashSet<fuente_financiacion>();
            this.fuente_financiacion3 = new HashSet<fuente_financiacion>();
            this.incorporacion_presupuestal = new HashSet<incorporacion_presupuestal>();
            this.incorporacion_presupuestal1 = new HashSet<incorporacion_presupuestal>();
            this.indicador = new HashSet<indicador>();
            this.insumo = new HashSet<insumo>();
            this.lista_indicador = new HashSet<lista_indicador>();
            this.lista_indicador1 = new HashSet<lista_indicador>();
            this.producto = new HashSet<producto>();
            this.proyecto = new HashSet<proyecto>();
            this.proyecto1 = new HashSet<proyecto>();
        }
    
        public int id { get; set; }
        public Nullable<int> unidades { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int lis_nombre_id { get; set; }
    
        public virtual ICollection<actividad> actividad { get; set; }
        public virtual ICollection<actividad_mga> actividad_mga { get; set; }
        public virtual ICollection<acuerdoAprobacion> acuerdoAprobacion { get; set; }
        public virtual ICollection<auditoria> auditoria { get; set; }
        public virtual ICollection<cuenta> cuenta { get; set; }
        public virtual ICollection<cumplimiento_requisitos> cumplimiento_requisitos { get; set; }
        public virtual ICollection<fuente_financiacion> fuente_financiacion { get; set; }
        public virtual ICollection<fuente_financiacion> fuente_financiacion1 { get; set; }
        public virtual ICollection<fuente_financiacion> fuente_financiacion2 { get; set; }
        public virtual ICollection<fuente_financiacion> fuente_financiacion3 { get; set; }
        public virtual ICollection<incorporacion_presupuestal> incorporacion_presupuestal { get; set; }
        public virtual ICollection<incorporacion_presupuestal> incorporacion_presupuestal1 { get; set; }
        public virtual ICollection<indicador> indicador { get; set; }
        public virtual ICollection<insumo> insumo { get; set; }
        public virtual lis_nombre lis_nombre { get; set; }
        public virtual ICollection<lista_indicador> lista_indicador { get; set; }
        public virtual ICollection<lista_indicador> lista_indicador1 { get; set; }
        public virtual ICollection<producto> producto { get; set; }
        public virtual ICollection<proyecto> proyecto { get; set; }
        public virtual ICollection<proyecto> proyecto1 { get; set; }
    }
}
