//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class lis_nombre
    {
        public lis_nombre()
        {
            this.lis_detalle = new HashSet<lis_detalle>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<lis_detalle> lis_detalle { get; set; }
    }
}
