//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_indicador
    {
        public lista_indicador()
        {
            this.indicador_gestion = new HashSet<indicador_gestion>();
            this.indicador_producto = new HashSet<indicador_producto>();
        }
    
        public int id { get; set; }
        public int lis_detalle_id_tipoindicador { get; set; }
        public int lis_detalle_id_sector { get; set; }
        public string codigo_indicador { get; set; }
        public string nombre_indicador { get; set; }
        public string unidad { get; set; }
        public string formula { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<indicador_gestion> indicador_gestion { get; set; }
        public virtual ICollection<indicador_producto> indicador_producto { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual lis_detalle lis_detalle1 { get; set; }
    }
}
