//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_gesproyEntities : DbContext
    {
        public bd_gesproyEntities()
            : base("name=bd_gesproyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<actividad_detalle> actividad_detalle { get; set; }
        public virtual DbSet<actividad_mga> actividad_mga { get; set; }
        public virtual DbSet<acuerdoAprobacion> acuerdoAprobacion { get; set; }
        public virtual DbSet<alerta> alerta { get; set; }
        public virtual DbSet<auditoria> auditoria { get; set; }
        public virtual DbSet<contactoEntidadEjecutora> contactoEntidadEjecutora { get; set; }
        public virtual DbSet<contactoEntidadEjecutora_has_entidadEjecutora> contactoEntidadEjecutora_has_entidadEjecutora { get; set; }
        public virtual DbSet<cuenta> cuenta { get; set; }
        public virtual DbSet<cumplimiento_requisitos> cumplimiento_requisitos { get; set; }
        public virtual DbSet<entidadEjecutora> entidadEjecutora { get; set; }
        public virtual DbSet<fuente_financiacion> fuente_financiacion { get; set; }
        public virtual DbSet<fuente_financiacion_detalle> fuente_financiacion_detalle { get; set; }
        public virtual DbSet<fuente_financiacion_has_proyecto> fuente_financiacion_has_proyecto { get; set; }
        public virtual DbSet<incorporacion_presupuestal> incorporacion_presupuestal { get; set; }
        public virtual DbSet<indicador> indicador { get; set; }
        public virtual DbSet<indicador_gestion> indicador_gestion { get; set; }
        public virtual DbSet<indicador_gestion_detalle> indicador_gestion_detalle { get; set; }
        public virtual DbSet<indicador_producto> indicador_producto { get; set; }
        public virtual DbSet<indicador_producto_detalle> indicador_producto_detalle { get; set; }
        public virtual DbSet<insumo> insumo { get; set; }
        public virtual DbSet<lis_detalle> lis_detalle { get; set; }
        public virtual DbSet<lis_nombre> lis_nombre { get; set; }
        public virtual DbSet<lista_indicador> lista_indicador { get; set; }
        public virtual DbSet<objetivo_especifico> objetivo_especifico { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<proyecto> proyecto { get; set; }
        public virtual DbSet<proyecto_has_usuario_has_rol> proyecto_has_usuario_has_rol { get; set; }
        public virtual DbSet<reintegro> reintegro { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rubro> rubro { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
