//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.actividad_mga = new HashSet<actividad_mga>();
            this.indicador_producto = new HashSet<indicador_producto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<double> cantidad { get; set; }
        public int objetivo_especifico_id { get; set; }
        public int lis_detalle_id_unidadmedida { get; set; }
    
        public virtual ICollection<actividad_mga> actividad_mga { get; set; }
        public virtual ICollection<indicador_producto> indicador_producto { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual objetivo_especifico objetivo_especifico { get; set; }
    }
}
