//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto
    {
        public proyecto()
        {
            this.acuerdoAprobacion = new HashSet<acuerdoAprobacion>();
            this.alerta = new HashSet<alerta>();
            this.auditoria = new HashSet<auditoria>();
            this.cuenta = new HashSet<cuenta>();
            this.fuente_financiacion_has_proyecto = new HashSet<fuente_financiacion_has_proyecto>();
            this.incorporacion_presupuestal = new HashSet<incorporacion_presupuestal>();
            this.indicador = new HashSet<indicador>();
            this.objetivo_especifico = new HashSet<objetivo_especifico>();
            this.proyecto_has_usuario_has_rol = new HashSet<proyecto_has_usuario_has_rol>();
        }
    
        public int bpin { get; set; }
        public string nombre { get; set; }
        public string objetivo_general { get; set; }
        public Nullable<int> ano_final { get; set; }
        public Nullable<int> ano_inicial { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public int entidadEjecutora_idEntidadEjecutora { get; set; }
        public Nullable<double> ava_fisico { get; set; }
        public Nullable<double> ava_financiero { get; set; }
        public Nullable<int> num_beneficiarios { get; set; }
        public Nullable<int> total_proyecto { get; set; }
        public int lis_detalle_id_sector { get; set; }
        public int lis_detalle_id_localizacion { get; set; }
    
        public virtual ICollection<acuerdoAprobacion> acuerdoAprobacion { get; set; }
        public virtual ICollection<alerta> alerta { get; set; }
        public virtual ICollection<auditoria> auditoria { get; set; }
        public virtual ICollection<cuenta> cuenta { get; set; }
        public virtual entidadEjecutora entidadEjecutora { get; set; }
        public virtual ICollection<fuente_financiacion_has_proyecto> fuente_financiacion_has_proyecto { get; set; }
        public virtual ICollection<incorporacion_presupuestal> incorporacion_presupuestal { get; set; }
        public virtual ICollection<indicador> indicador { get; set; }
        public virtual lis_detalle lis_detalle { get; set; }
        public virtual lis_detalle lis_detalle1 { get; set; }
        public virtual ICollection<objetivo_especifico> objetivo_especifico { get; set; }
        public virtual ICollection<proyecto_has_usuario_has_rol> proyecto_has_usuario_has_rol { get; set; }
    }
}
