//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto_has_usuario_has_rol
    {
        public int id { get; set; }
        public int usuario_idUsuario { get; set; }
        public int rol_idRol { get; set; }
        public int proyecto_bpin { get; set; }
    
        public virtual proyecto proyecto { get; set; }
        public virtual rol rol { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
