//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class reintegro
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string documento { get; set; }
        public Nullable<int> num_documento { get; set; }
        public Nullable<double> rendimiento_financiero { get; set; }
        public Nullable<double> valor_reintegro_no_ejecutado { get; set; }
        public Nullable<double> total_reintegro { get; set; }
        public int cuenta_numero { get; set; }
    
        public virtual cuenta cuenta { get; set; }
    }
}
