//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol
    {
        public rol()
        {
            this.proyecto_has_usuario_has_rol = new HashSet<proyecto_has_usuario_has_rol>();
        }
    
        public int idRol { get; set; }
        public string nombreRol { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<proyecto_has_usuario_has_rol> proyecto_has_usuario_has_rol { get; set; }
    }
}
