//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.proyecto_has_usuario_has_rol = new HashSet<proyecto_has_usuario_has_rol>();
        }
    
        public int idUsuario { get; set; }
        public string tipoIdentificacion { get; set; }
        public string identificacion { get; set; }
        public string nombreUno { get; set; }
        public string nombreDos { get; set; }
        public string apellidoUno { get; set; }
        public string apellidoDos { get; set; }
        public string telFijo { get; set; }
        public string telCelular { get; set; }
        public string email { get; set; }
        public string tipoVinculacion { get; set; }
        public string cargo { get; set; }
        public string fechaCulminacion { get; set; }
        public string usuario1 { get; set; }
        public string clave { get; set; }
    
        public virtual ICollection<proyecto_has_usuario_has_rol> proyecto_has_usuario_has_rol { get; set; }
    }
}
